image:
  repository: wandb/local
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

serviceAccount:
  create: true
  name: "wandb-sa"

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: 
        - /
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: true
  size: 5Gi
  storageClass: "standard"

env:
  # Example environment variables for local wandb. 
  # Adjust them if needed or add more advanced config, 
  # e.g., a custom user secret or domain settings.
  WANDB_API_KEY: "<YOUR_API_KEY>"
  WANDB_NAME: "my-wandb-server"