apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wandb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "wandb.name" . }}
    helm.sh/chart: {{ include "wandb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}